engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

exclude_paths:
- db/
- spec/
- app/assets/javascripts/bootstrap.js
- app/assets/javascripts/jquery.dataTables.js
- "**/vendor/**/*"

ratings:
   paths:
   - Gemfile.lock
   - "**.rb"
   - "**.erb"
   - "**.js"
   - "**.css"
