# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b045dbd6cd49c71c7453ba4e9c464996971a8d3dd5cb9aa8c24e9dc78ec04a8c3f4dedf3a12257f6cf3f107948b6cde42868fbd65adc5b969aacf40fdb93c4a8

test:
  secret_key_base: 9a1b130bfabe65e2f5c5701e07c8022e5cfdf249e5793454a0224781be42eb3f31ae0ed14259ca58de957ed02428ff6f323d5976c830e37a820bb4fa50d1280f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
