wayback_timemap_uri: "https://swap.stanford.edu/timemap/link/"
wayback_uri: "https://wayback-dev.stanford.edu/*/"
image_stacks_uri: "http://example.stanford.edu"
purl_url: "http://purl-test.stanford.edu/"
